"use strict";

define({
    plaqueMessageSmall: {},
    buttonText: {},
    winningNumbersTitle: {
        fontFamily: 'oswald',
        fontWeight: 'bold',
        fontSize: 36,
        //fill: 'fontColourLuckyNumberTitle'
        fill: ["#ffffff", "#b2b6c1"] //fillGradientStops: [0.5, 0.5],

    },
    playerNumbersTitle: {
        fontFamily: 'oswald',
        fontWeight: 'bold',
        fontSize: 36,
        fill: 'fontColourYourNumberTitle',
        lineJoin: "round",
        miterLimit: 30
    },
    prizeValueNoWin: {
        fontFamily: 'oswald',
        fontSize: 25,
        //dropShadow: true,
        fontWeight: 'bold',
        fill: '#fcc87f',
        //["#9b9a7a", "#62614d"],
        lineJoin: "round",
        miterLimit: 30 //alpha: 0.5 //fill: ["#b7b7b9", "#5c5c5f"] 

    },
    howToPlayTextCenter: {
        "dropShadow": true,
        "dropShadowAngle": 1.7,
        "dropShadowBlur": 1,
        "dropShadowColor": "black",
        "dropShadowDistance": 2,
        "fontSize": 35,
        "fill": '#dddddd',
        "fontFamily": 'oswald',
        "align": "center",
        "wordWrap": true,
        "padding": 10
    },
    howToPlayText: {
        fill: 'fontColourTutorialBodyText',
        fontFamily: 'oswald',
        fontSize: 30,
        wordWrap: true,
        align: "center",
        padding: 20
    },
    collectBonusValuePicker: {
        "dropShadow": true,
        "dropShadowAngle": 1.7,
        "dropShadowBlur": 5,
        "dropShadowColor": "#421500",
        "dropShadowDistance": 0,
        "fill": "#ffffff",
        "fontSize": 60,
        "lineJoin": "round",
        "miterLimit": 28,
        "stroke": "#421500",
        "strokeThickness": 2,
        "fontFamily": "Franklin-Gothic-Condensed"
    },
    prizeValueWin: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'bold',
        lineJoin: "round",
        miterLimit: 30,
        //fill: ["#f3da30", "#c7691f"],
        fill: ["#fff135", "#ef9d28"],
        dropShadow: true,
        dropShadowAngle: 1,
        dropShadowBlur: 2,
        dropShadowDistance: 0,
        dropShadowColor: "#000000",
        stroke: "#000000",
        strokeThickness: 4 //fillGradientStops: [0.5, 0.5]

    },
    winUpTo: {
        fontSize: 100,
        fontFamily: 'oswald',
        fontWeight: 'bold',
        fill: ["#fffffd", "#fffca3", "#fef546", "#fead00", "#ff6600"],
        "dropShadow": true,
        "dropShadowAngle": -1,
        "dropShadowBlur": 22,
        "dropShadowColor": "#00085b",
        "lineJoin": "round",
        "miterLimit": 0,
        "padding": 12,
        stroke: "#ffffff",
        strokeThickness: 4
    },
    infoBar: {
        fontSize: 28,
        fontFamily: 'oswald',
        fontWeight: "normal",
        dropShadow: true,
        dropShadowAngle: 1,
        dropShadowBlur: 33,
        dropShadowDistance: 0,
        fill: 'FontColourTimeOutMessage',
        lineJoin: "round",
        miterLimit: 30,
        align: 'center',
        padding: 4

    },
    winUpToTitle: {
        fontSize: 45,
        fontFamily: 'oswald',
        fontWeight: "bold",
        align: "left",
        dropShadowAngle: 1,
        dropShadowBlur: 8,
        dropShadowColor: '#ffffff',
        dropShadowDistance: 1,
        dropShadowQuality: 15,
        fill: 'fontColourWinUpToTitle',
        //fill: ["#cec246", "#fffee0"],
        //fillGradientStops: [0.3, 0.5, 0.5, 0.5, 0.6],
        lineJoin: "round",
        miterLimit: 30,
        padding: 41,
        stroke: "#ffffff",
        strokeThickness: 5
    },
    bonusLabel: {
        fontFamily: 'ImpactCondensed',
        fontSize: 44,
        fontWeight: 'normal',
        dropShadow: true,
        dropShadowAngle: 1,
        dropShadowBlur: 5,
        dropShadowDistance: 2,
        lineJoin: "round",
        miterLimit: 30,
        fill: ["#ffffff", "#b2b6c1"] //strokeThickness: 5

    },
    bonusLabelGold: {
        fontFamily: 'ImpactCondensed',
        fontSize: 44,
        fontWeight: "normal",
        dropShadow: true,
        dropShadowAngle: 1,
        dropShadowBlur: 5,
        dropShadowDistance: 2,
        fill: ["#cec246", "#fffee0"],
        //fillGradientStops: [0.5, 0.5],
        lineJoin: "round",
        miterLimit: 30,
        stroke: "#000000",
        strokeThickness: 1,
        padding: 41 //stroke: "#603c06",
        //strokeThickness: 5

    },
    bonusWin: {
        fontFamily: 'oswald',
        fontSize: 44,
        fontWeight: 'bold',
        fill: 'fontColourBonusWin',
        lineJoin: "round",
        miterLimit: 30
    },
    bonusNoWin: {
        fontFamily: 'oswald',
        fontSize: 44,
        fontWeight: 'bold',
        lineJoin: "round",
        miterLimit: 30
    },
    losePlaqueBody: {
        fontFamily: 'oswald',
        fontSize: 70,
        fontWeight: 'normal',
        dropShadow: true,
        dropShadowAngle: 1,
        dropShadowBlur: 5,
        dropShadowDistance: 2,
        //fill: ["#ffffff", "#9b9b9b", "#ffffff"],
        //fillGradientStops: [0.2, 0.5, 0.7],
        //fill: 'fontColourEndOfGameMessageNoWinBodyText',
        fill: '#fcf0d2',
        align: 'center',
        stroke: "#000000",
        padding: 5,
        //strokeThickness: 5,
        //lineJoin: "round",
        miterLimit: 30
    },
    // This is for non-plaque present in endGame
    winPlaqueBodyNoPlaque: {
        fontFamily: 'oswald',
        fontSize: 60,
        fontWeight: 'normal',
        dropShadow: true,
        dropShadowColor: "#FFF9BB",
        dropShadowAngle: 1,
        dropShadowBlur: 5,
        dropShadowDistance: 1,
        //fill: ["#ffffff", "#9b9b9b", "#ffffff"],
        fill: "#085600",
        //'fontColourTutorialOKButtonOver',
        //fillGradientStops: [0.2, 0.5, 0.7],
        align: 'center',
        stroke: "#FFF9BB",
        strokeThickness: 3,
        lineJoin: "round",
        miterLimit: 30,
        padding: 5
    },
    // This is for plaque present in the endGame
    winPlaqueBody: {
        fontFamily: 'oswald',
        fontSize: 50,
        fontWeight: 'normal',
        dropShadow: true,
        dropShadowColor: "#fcf04a",
        dropShadowAngle: 1,
        dropShadowBlur: 5,
        dropShadowDistance: 1,
        //fill: ["#ffffff", "#9b9b9b", "#ffffff"],
        fill: 'fontColourTutorialOKButtonOver',
        //fillGradientStops: [0.2, 0.5, 0.7],
        align: 'center',
        stroke: "#fcf04a",
        strokeThickness: 8,
        lineJoin: "round",
        miterLimit: 30,
        padding: 5
    },
    winPlaqueValue: {
        fontFamily: 'oswald',
        fontSize: 90,
        fontWeight: 'normal',
        dropShadow: true,
        dropShadowAngle: 1,
        dropShadowBlur: 15,
        dropShadowColor: '#AF009C',
        dropShadowDistance: 1,
        dropShadowQuality: 15,
        fill: ["#EA4DFD", "#E400FF", "#6A00A7"],
        //padding: 41,
        stroke: "#f7d699",
        strokeThickness: 5,
        lineJoin: "round",
        miterLimit: 30
    },
    bonusWinTitle: {
        fontFamily: 'oswald',
        fontSize: 60,
        fontWeight: 'normal',
        dropShadow: true,
        dropShadowColor: "#FFF14F",
        dropShadowAngle: 1,
        dropShadowBlur: 15,
        dropShadowDistance: 1,
        //fill: ["#ffffff", "#9b9b9b", "#ffffff"],
        fill: "#AE00FF",
        //'fontColourTutorialOKButtonOver',
        //fillGradientStops: [0.2, 0.5, 0.7],
        align: 'center',
        stroke: "#FFF14F",
        strokeThickness: 8,
        lineJoin: "round",
        miterLimit: 30
    },
    bonusWinValue: {
        fontFamily: 'oswald',
        fontSize: 120,
        fontWeight: 'normal',
        dropShadow: true,
        dropShadowAngle: 1,
        dropShadowBlur: 15,
        dropShadowColor: '#AF009C',
        dropShadowDistance: 1,
        dropShadowQuality: 15,
        fill: ["#EA4DFD", "#E400FF", "#6A00A7"],
        padding: 41,
        stroke: "#f7d699",
        strokeThickness: 5,
        lineJoin: "round",
        miterLimit: 30
    },
    bonusInfo: {
        fontFamily: 'oswald',
        fontSize: 22,
        fontWeight: 'normal',
        //dropShadow: true,
        //dropShadowAlpha: 0.5,
        //dropShadowAngle: 1.7,
        //dropShadowBlur: 11,
        //dropShadowDistance: 3,
        padding: 4,
        stroke: "#48470b",
        strokeThickness: 5,
        align: 'left',
        lineJoin: "round",
        miterLimit: 30,
        fill: ["#d7ffa1", "#a7dc5f"] //fillGradientStops: [0.5, 0.5, 0.6, 0.7],
        //strokeThickness: 5

    },
    bonusInfo2: {
        fontFamily: 'oswald',
        fontSize: 22,
        fontWeight: 'normal',
        //dropShadow: true,
        //dropShadowAlpha: 0.5,
        //dropShadowColor: '#68441b',
        //dropShadowAngle: 1,
        //dropShadowBlur: 5,
        //dropShadowDistance: 3,
        padding: 4,
        stroke: "#7e3a1f",
        strokeThickness: 5,
        align: 'left',
        lineJoin: "round",
        miterLimit: 30,
        fill: '#fff64d' //fill: ["#97d3e6", "#c7e8f1"],
        //fillGradientStops: [0, 0.5, 0.6, 0.7],
        //strokeThickness: 5

    },
    collectPrizeRed: {
        fontFamily: 'oswald',
        fontSize: 35,
        fontWeight: 'normal',
        dropShadow: true,
        dropShadowAlpha: 0.5,
        dropShadowAngle: 1.7,
        dropShadowBlur: 11,
        dropShadowDistance: 3,
        align: 'left',
        lineJoin: "round",
        miterLimit: 30,
        fill: '#de0812'
    },
    collectPrizeOrange: {
        fontFamily: 'oswald',
        fontSize: 35,
        fontWeight: 'normal',
        dropShadow: true,
        dropShadowAlpha: 0.5,
        dropShadowAngle: 1.7,
        dropShadowBlur: 11,
        dropShadowDistance: 3,
        align: 'left',
        lineJoin: "round",
        miterLimit: 30,
        fill: '#ffff0e'
    },
    collectPrizeYellow: {
        fontFamily: 'oswald',
        fontSize: 35,
        fontWeight: 'normal',
        dropShadow: true,
        dropShadowAlpha: 0.5,
        dropShadowAngle: 1.7,
        dropShadowBlur: 11,
        dropShadowDistance: 3,
        align: 'left',
        lineJoin: "round",
        miterLimit: 30,
        fill: '#45e005'
    },
    collectPrizeGreen: {
        fontFamily: 'oswald',
        fontSize: 35,
        fontWeight: 'normal',
        dropShadow: true,
        dropShadowAlpha: 0.5,
        dropShadowAngle: 1.7,
        dropShadowBlur: 11,
        dropShadowDistance: 3,
        align: 'left',
        lineJoin: "round",
        miterLimit: 30,
        fill: '#db57dc'
    },
    collectMeterInfo: {
        fontFamily: 'oswald',
        fontSize: 25,
        fontWeight: 'normal',
        dropShadow: true,
        dropShadowAlpha: 0.5,
        dropShadowAngle: 1.7,
        dropShadowBlur: 11,
        dropShadowDistance: 3,
        align: 'center',
        lineJoin: "round",
        miterLimit: 30,
        fill: '#ffffff'
    },
    tutorialOKButtonEnabled: {
        fontFamily: 'oswald',
        fontSize: 38,
        fill: 'fontColourMainButtonEnabled',
        //fill: 'fontColourTutorialOKButtonEnabled',
        padding: 10
    },
    tutorialOKButtonOver: {
        fontFamily: 'oswald',
        fontSize: 38,
        //fill: 'fontColourTutorialOKButtonOver',
        fill: 'fontColourMainButtonEnabled',
        padding: 10
    },
    revealAllEnabled: {
        fontFamily: 'oswald',
        //fontWeight: 'bold',
        fontSize: 28,
        align: 'center',
        fill: 'fontColourMainButtonEnabled',
        padding: 10
    },
    revealAllPressed: {
        fontFamily: 'oswald',
        //fontWeight: 'bold',
        fontSize: 30,
        align: 'center',
        fill: 'fontColourMainButtonEnabled',
        padding: 10
    },
    revealAllDisabled: {
        fontFamily: 'oswald',
        //fontWeight: 'bold',
        fontSize: 28,
        align: 'center',
        fill: '#ffffff',
        padding: 10
    },
    buyButtonLandEnabled: {
        fontFamily: 'oswald',
        fontSize: 38,
        //fill: 'fontColourTutorialOKButtonPressed',
        fill: '#000000',
        padding: 10
    },
    buyButtonLandPressed: {
        fontFamily: 'oswald',
        fontSize: 43,
        //fill: 'fontColourMainButtonPressed',
        fill: '#000000' //padding: 10,

    },
    tutorialOKButtonPressed: {
        fontFamily: 'oswald',
        fontSize: 48,
        //fill: 'fontColourTutorialOKButtonPressed',
        fill: 'fontColourMainButtonEnabled',
        padding: 10
    },
    mainButtonEnabled: {
        fontFamily: 'oswald',
        fontSize: 38,
        fill: 'fontColourMainButtonEnabled' //fill: 'fontColourMainButtonEnabled',
        //padding: 10,

    },
    mainButtonDisabled: {
        fontFamily: 'oswald',
        fontSize: 38,
        //fill: 'fontColourMainButtonDisabled',
        fill: '#ffffff' //padding: 10,

    },
    mainButtonOver: {
        fontFamily: 'oswald',
        fontSize: 38,
        //fill: 'fontColourMainButtonOver',
        fill: 'fontColourMainButtonEnabled' //padding: 10,

    },
    mainButtonPressed: {
        fontFamily: 'oswald',
        fontSize: 43,
        //fill: 'fontColourMainButtonPressed',
        fill: '#000000' //padding: 10,

    }
});